import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <LoginBtn/>
        </div>
        {children}
      </body>
    </html>
  );
}
