import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 로그인 정보를 출력하는 기능
  let session = await getServerSession(authOptions) // 서버 컴포넌트, 서버 기능 안에서 사용 가능, 비동기 함수이므로 await 과 함께 사용
  console.log("✨ session: ", session)
  return (
    <html lang="ko">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <LoginBtn/>
        </div>
        {children}
      </body>
    </html>
  );
}
